const fs = require('fs');
const path = require('path');
const gettextParser = require('gettext-parser');

// collect from i18nextKey
const inconsistentI18NKeys = {
  greaterThan: 'op-gt',
  greaterThanOrEqualTo: 'op-gte',
  equal: 'op-equal',
  lessThan: 'op-lt',
  lessThanOrEqualTo: 'op-lte',
  defaultTimeOption: 'op-default',
  absoluteTimeOption: 'op-absolute',
  relativeTimeOption: 'op-relative',
  search: 'Search',
  cancel: 'Cancel',
  ok: 'OK',
  runningWorkflows: 'Running Workflows',
  revenue: 'Revenue',
  pageviews: 'Pageviews',
  transactions: 'Transactions',
  sessions: 'Sessions',
  sessionExpired: 'Session Has Expired, Please Log in Again to Continue!',
  checkLogin: 'Please Check your Username and Password.',
  revenuePerTransaction: 'Revenue Per Transaction',
  avgRevenuePerTransaction: 'Average Revenue Per Transaction',
  acquisition: 'Acquisition',
  users: 'Users',
  member: 'Member',
  revenueBySources: 'Revenue by Sources',
  pageviewBySources: 'Pageview by Sources',
  byTag: 'By Tag',
  reset: 'Reset',
  createWorkflow: 'Create New Workflow',
  cloneWorkflow: 'Clone New Workflow',
  name: 'Name',
  firstName: 'First Name',
  lastName: 'last Name',
  furiganaFirstName: 'Furigana First Name',
  furiganaLastName: 'Furigana Last Name',
  sn: 'SN',
  turnOn: 'Turn On',
  turnOff: 'Turn Off',
  prerender: 'Prerender',
  finishAndActive: 'Finish and Active',
  finish: 'Finish',
  saveAsDraft: 'Save as Draft',
  total: 'Total',
  none: 'None',
  loading: 'Loading...',
  download: 'Download',
  share: 'Share',
  true: 'True',
  false: 'False',
  file: 'File',
  change: 'Change',
  spreadsheetField: 'Spreadsheet Field',
  MAField: 'MA Field',
  pleaseSelect: 'Please Select',
  traditionalChinese: 'Traditional Chinese',
  english: 'English',
  japanese: 'Japanese',
  dashboard: 'Dashboard',
  workflow: 'Workflow',
  editor: 'Editor',
  audience: 'Audience',
  menuAudience: 'Menu Audience',
  addAudience: 'Add Audience',
  product: 'Product',
  menuProduct: 'Menu Product',
  addProduct: 'Add Product',
  utm: 'UTM',
  menuUTM: 'Menu UTM',
  addUtm: 'Add UTM',
  addTag: 'Add Tag',
  manual: 'Manual',
  logout: 'Log Out',
  import: 'Import',
  export: 'Export',
  add: 'Add',
  update: 'Update',
  searchKeyword: 'Search Keyword',
  tag: 'Tag',
  phone: 'Phone',
  email: 'Email',
  productNumber: 'Product Number',
  category: 'Category',
  campaign: 'Campaign',
  medium: 'Medium',
  source: 'Source',
  memberLevel: 'Member Level',
  folder: 'Folder',
  sms: 'SMS',
  line: 'Line',
  webpopup: 'web-popup',
  webpush: 'web-push',
  time: 'Time',
  count: 'Count',
  addNewType: 'Add New Type',
  hasBeenAdded: 'Has Been Added',
  categoryName: 'Category Name',
  backToList: 'Back To List',
  title: 'Title',
  previewText: 'Preview Text',
  creator: 'Creator',
  draft: 'Draft',
  testEmail: 'Test Email',
  testMemberEmail: 'Test Member Email',
  setAsSample: 'Set as Sample',
  sendTestEmail: 'Send Test Email',
  insertTag: 'Insert Tag',
  status: 'Status',
  click: 'Click',
  linkedReport: 'report.table.LinkedReport',
  infoProductFeed: 'report.table.title.info.ProductFeed',
  totalSendLimit: 'TotalSendLimit',
  totalSendLimitDesc: 'TotalSendLimitDesc',
  sendPoint: 'Send Point',
  sendQuantity: 'Send Quantity',
  numOfTestSend: 'Num Of Test Send',
  numOfTestPoint: 'Num Of Test Point',
  deliveredRate: 'Delivered Rate',
  notClick: 'Not Click',
  buy: 'Buy',
  notOpenEmail: 'Not Open',
  tagList: 'Tag List',
  startingDate: 'Starting Date',
  endingDate: 'Ending Date',
  textOverflow: 'Text Overflow',
  edit: 'Edit',
  delete: 'Delete',
  setProductFeedTag: 'Set ProductFeed Tag',
  login: 'Log In',
  previewAudience: 'Preview Audience',
  previewAudienceCount: 'Preview Audience Count',
  previewAudienceError: 'Preview Audience Error',
  goEditor: 'Go Editor',
  lastEditor: 'Last Editor',
  formatTemplate: 'Format Template',
  formatDownload: 'Format Download',
  selectFormatTemplate: 'Select Format Template',
  customerFormatTemplate: 'Customer Format Template',
  purchaseInformationFormatTemplate: 'Purchase Information Format Template',
  giftVoucherFormatTemplate: 'Gift Voucher Format Template',
  fileImportInProgress: 'File Import In Progress',
  fileImportSuccessfully: 'File Import Successfully',
  fileImporting:
    'Importing files now, but you can click "Import Status" to view the import results.',
  missingMergeKey: 'Please select merge key',
  missingSpecifiedField: 'Non-specified field in imported data',
  unreadNotice: 'Unread Notice',
  msgNoNotification: 'No Notification',
  noticeFileImportSuccessfully: 'Notice of Importing File Successfully',
  noticeFileImportFailed: 'Notice of Importing File Failed',
  productFeedUrlHeader: 'Product Feed URL Header',
  priceDisplayLanguageHeader: 'Price Display Language Header',
  priceDisplayLanguage: 'Price Display Language',
  recentView: 'Recent View',
  abandonedCart: 'Abandoned Cart',
  productTags: 'Product Tags',
  productCategory: 'Product Category',
  productsAddedToTheWishList: 'Products added to the wish list',
  maxDaysAgoReminder: 'Max DaysAgo Reminder',
  emailPreviewReminder: 'Email Preview Reminder',
  giftVoucherFeed: 'Gift Voucher Feed',
  setting: 'Setting',
  edmSetting: 'EDM Setting',
  emailSender: 'Email Sender',
  yourEmailSender: 'Your Email Sender',
  emailTitle: 'Email Title (Your Company Name)',
  yourEmailTitle: 'Your Email Title',
  unsubscribeSetting: 'Unsubscribe Setting',
  uploadImage: 'Upload Image',
  testMemberSetting: 'Test Member Setting',
  yourText: 'Your Text',
  workflowName: 'Workflow Name',
  workflowNodeName: 'Workflow Node Name',
  currentAudiences: 'Current Audiences',
  currentPoints: 'Current Points',
  totalSpentPoints: 'Total Spent Points',
  advancedSpendPoints: 'Advanced Spent Points',
  channelName: 'Channel Name',
  lineChannelId: 'Line Channel ID',
  lineChannelSecret: 'Line Channel Secret',
  LineAccessToken: 'Line Access Token',
  refreshToken: 'Refresh Token',
  webhook: 'Webhook',
  webhookURL: 'Webhook URL',
  webhookForwardingSetting: 'Webhook Forwarding Setting',
  channel: 'Channel',
  mediaChannel: 'Media Channel',
  account: 'Account',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  changePassword: 'Change Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  yourTestId: 'Your Test ID',
  customName: 'Your Custom Name',
  edm: 'EDM',
  googleTid: 'Google Tracking ID',
  dailyMessageLimit: 'Daily Message Limit',
  sevenDayMessageLimit: 'Seven Day Message Limit',
  fourteenDayMessageLimit: 'Fourteen Day Message Limit',
  thirtyDayMessageLimit: 'Thirty Day Message Limit',
  doNotBother: 'Turn on Do Not Bother',
  doNotDisturbInDays: 'Do Not Disturb in Days',
  send: 'Send',
  sendSetting: 'Send Setting',
  fbProductFeedUrl: 'Product Feed URL',
  trackingConfig: 'Tracking Config',
  partnerApiKey: 'Partner API Key',
  sendingConfig: 'Sending Config',
  doNotDisturbConfig: 'Do Not Disturb Config',
  sendingConfigByChannel: 'Sending Config by Channel',
  generalSendingConfig: 'General Sending Config',
  audienceDataMerge: 'Customer Information Consolidation',
  headlessMergeDescription:
    'Customer information without a member id will be automatically integrated into the corresponding member information.',
  trackingType: 'Tracking Type',
  chooseWorkflowGroup: 'Choose Workflow Group',
  numOfSelectedLinks: 'Num Of Selected Links',
  chooseType: 'Choose Type',
  chooseTypePlaceholder: 'choose Tracking Type',
  chooseWorkflow: 'Choose Workflow',
  chooseWorkPlaceholder: 'Choose Workflow',
  chooseNode: 'Choose Node',
  chooseNodePlaceholder: 'Node',
  chooseLink: 'Choose Link',
  chooseLinkPlaceholder: 'Links in Emai',
  linkList: 'Link List',
  chooseEmailNode: 'Choose Email Node',
  chooseEmailNodePlaceholder: 'Choose Email Node',
  chooseSMSGroup: 'Choose SMS Group',
  chooseSMSGroupPlaceholder: 'Choose SMS Group',
  chooseSMSTemplate: 'Choose SMS Template',
  chooseSMSPlaceholder: 'Choose SMS',
  test: 'Test',
  emoji: 'Emoji',
  text: 'Text',
  image: 'Image',
  linePreviewHolder: 'Text in Preview & Notification',
  addImage: 'Add Image',
  addText: 'Add Text',
  sendLineText: 'Send Line Text',
  lineMsgDia: 'Line Message Dialog',
  added: 'Added',
  video: 'Video',
  addVideo: 'Add Video',
  buttonText: 'Button Text',
  carousel: 'Carousel',
  addCarousel: 'Add Carousel',
  imageSource: 'Image Source',
  normal: 'Normal',
  linkText: 'Link Text',
  daysAgo: 'Days Ago',
  numOfItem: 'Number of Items',
  viewTogether: 'View Together',
  buyTogether: 'Buy Together',
  highPageViewItem: 'High Page View Item',
  hotItem: 'Hot Item',
  carouselType: 'Carousel Type',
  carouselImageCard: 'Carousel Image Card',
  carouselImageOnly: 'Carousel Image Only',
  carouselMainText: 'Carousel Main Text',
  carouselDescText: 'Carousel Desc Text',
  chooseLineChannel: 'Choose Line Channel',
  chooseLineGroup: 'Choose Line Group',
  chooseLineTemplate: 'Choose Line Template',
  chooseWebPopupGroup: 'Choose Web Popup Group',
  chooseWebPopupTemplate: 'Choose Web Popup Template',
  chooseCrescendoGroup: 'Choose Crescendo Group',
  chooseCrescendoTemplate: 'Choose Crescendo Template',
  repeatPnpEventMsg:
    'The following event already exists in the specified channel',
  uniquePnpEventMsg: 'in the same channel must not be repeated.',
  repeatIdMsg: 'The Id already exists and the Id must not be repeated.',
  'editor.line.reminder.aspectRatio13': 'Editor Line Reminder AspectRatio 1:3',
  'editor.line.errormsg.aspectRatioExceed13':
    'Editor Line Errormsg Aspect Ratio Exceed 1:3',
  date: 'Date',
  weekDay: 'Week Day',
  hour: 'Hour',
  report: 'Report',
  open: 'Open',
  exportAudiences: 'Export Audiences',
  previewAudiences: 'Preivew Audiences',
  'report.DeliveryTime': 'Delivery Time',
  'report.table.title.info.DeliveryTime': 'Delivery Time Info',
  selTemplate: 'Select Template Type',
  channelAddTitle: 'Add [NAME]',
  channelFieldName: '[NAME] name',
  channelAddItem: 'Add [TYPE]',
  channelCategoryHasBeenAdded: 'Category [NAME] Has Been Added',
  sendSMS: 'Send SMS',
  confirmLongTextMsg: 'Confirming Long Text Message',
  enableLongTextMsg: 'Enabling Long Text Message',
  alertOfLongTextMsg: 'Alert Of Long Text Message',
  reminderOfCheckingUrl: 'Reminder Of Checking Url',
  reminderOfConfirmLongTextMsg: 'Reminder Of Confirming Long Text Message',
  warningOfVariableInMsg: 'Warning Of Variable In Message',
  warningOfSendingLongTextMsg: 'Warning Of Sending Long Text Message',
  absoluteDate: 'Absolute Date',
  relativeTime: 'Relative Time',
  defaultNinetyDays: '90 Days ago',
  tagTimes: 'Add Tag Times',
  operator: 'Operator',
  activeTriggerCondition: 'Active Trigger Condition',
  audienceTrend: 'Audience Trend',
  tagAnalysis: 'Tag Analysis',
  getReport: 'Get Report',
  tagHistory: 'Tag History',
  tagReferenceTime: 'Tag Reference Time',
  tagAudienceChange: 'Tag Audience Change',
  revenueCv: 'Revenue / Transactions',
  settingExpire: 'Setting Expire Time',
  expirationDate: 'Expiration Date',
  expiresInDays: 'Expires in ... Days',
  allRecord: 'All Record',
  recordAudienceMonthly: 'Record Audience Monthly',
  watch: 'Watch',
  all: 'All',
  notActive: 'Not Active',
  'workflow.node.setting.personalizedSendTime': 'Personalized Delivery Time',
  ignoreDailyLimit: 'Ignore Daily Limit',
  ignoreNoSubscriber: 'Ignore No Subscriber',
  node: 'Node',
  template: 'Template',
  action: 'ACTION',
  actionTime: 'Action Time',
  now: 'Now',
  setTime: 'Set Time',
  repeat: 'Repeat',
  property: 'Property',
  value: 'Value',
  delay: 'Delay',
  month: 'Month',
  week: 'Week',
  day: 'Day',
  minute: 'Minute',
  second: 'Second',
  remove: 'Remove',
  tagging: 'Tagging',
  chooseNotificationGroup: 'Choose Notification Group',
  chooseNotificationTemplate: 'Choose Notification Template',
  every: 'Every',
  closeWorkflow: 'Close Customer Journey',
  general: 'General',
  advance: 'Advance',
  filter: 'Filter',
  columns: 'Columns',
  two: 'Two',
  three: 'Three',
  quantity: 'Quantity',
  previewEmail: 'Preview Email',
  htmlEdmTemplate: 'HTML EDM Template',
  chooseEmailChannel: 'Choose Email Channel',
  chooseEDMGroup: 'Choose EDM Group',
  chooseEDMTemplate: 'Choose EDM Template',
  gifError: 'GIF image should be less than 1MB, not wider than 600px',
  productFeedSupportOutlook: 'Product Feed Support Outlook',
  activityNumOfProduct: 'Number of Product',
  activityTotalTransaction: 'Total Transaction',
  activityProductList: 'Product List',
  activityProductImage: 'Product List Image',
  activityName: 'Event Name',
  activityPageName: 'Page Name',
  activityUrl: 'URL',
  activityShippingAddress: 'Shipping Address',
  activityconvenienceStoreAddress: 'Convenience Store Address',
  incompleteDataReminder: 'Incomplete Data Reminder',
  crescendo: 'Crescendo',
  crescendoToken: 'Crescendo Token',
  crescendoTemplate: 'Crescendo Template',
  clearAudiences: 'Clear Audiences',
  selectChannel: 'Select Channel',
  registrationEvent: 'Registration Event',
  pnpEventName: 'PNP Event Name',
  pnpIdSetting: 'PNP ID Setting',
  success: 'Success',
  refund: 'Refund',
  fail: 'Fail',
  shipped: 'Shipped',
  paid: 'Paid',
  preview: 'Preview',
  number: 'Number',
  yes: 'Yes',
  no: 'No',
  male: 'Male',
  female: 'Female',
  timeType: 'Time Type',
  site: 'Site',
  notification: 'Notification',
  startingTime: 'Start Time',
  completeTime: 'Complete Time',
  fileName: 'File Name',
  errorLog: 'Error Log',
  creationTime: 'Creation Time',
  lastModifiedTime: 'Last Modified Time',
  urlLimit: 'Url Must Start with http or https',
  registerType: 'Register Type',
  registerDate: 'Register Date',
  isoCode: 'ISO Code',
  unSet: 'Unset',
  days: 'Days',
  removeTagInAudiences: 'Remove Tag in Audiences',
  clearTagInAudiences: 'Delete Audiences by Tag',
  content: 'Content',
  currentWordCount: 'Current Word Count',
  noTemplate: 'No Template',
  selectTemplate: 'Select Template',
  addFolder: 'editor.CreateTemplate.default.AddFolder',
  profile: 'Profile',
  gender: 'Gender',
  sex: 'Gender',
  birthday: 'Birthday',
  isActive: 'Is Active',
  isFromBeacon: 'Is From Beacon',
  crmPk: 'CRM PK',
  isHeadlessAcc: 'Is Headless Account',
  isSubscriber: 'Is Subscriber',
  language: 'Language',
  country: 'Country',
  city: 'City',
  lineId: 'Line ID',
  apnsToken: 'Apns Token',
  fcmToken: 'FCM Token',
  googleId: 'Google ID',
  facebookId: 'Facebook ID',
  productId: 'Product ID',
  productSku: 'product SKU',
  itemGroupId: 'Item Group ID',
  price: 'Price',
  brand: 'Brand',
  variant: 'Variant',
  coupon: 'Coupon',
  productUrl: 'Product Url',
  productPhoto: 'Product Photo',
  originalPrice: 'Original Price',
  salePrice: 'On Sale',
  campaignId: 'UTM Campaign ID',
  utmContent: 'UTM Content',
  utmTerm: 'UTM Tern',
  indicatorPresentation: 'Indicator Presentation',
  purchaseHistory: 'Purchase History',
  browsingHistory: 'Browsing History',
  keyFormat: 'Key Format',
  appleAPNSCertificate: 'Apple APNS Certificate',
  apnsTopic: 'Apns Topic (Bundle ID)',
  authKeyId: 'Apns Auth Key ID',
  teamId: 'Team ID',
  fcmApiKey: 'FCM API Key',
  syncProductData: 'Sync Product Data',
  sent: 'Sent',
  bounce: 'Bounce',
  blocked: 'Blocked',
  spam: 'Spam',
  unsub: 'Unsubscribe',
  triggerType: 'Trigger Type',
  scrolling: 'Scrolling',
  eventCategoryName: 'Event Category Name',
  eventActionName: 'Event Action Name',
  withLogined: 'with Logined',
  WithLine: 'With Line',
  disable: 'Disable',
  haveLine: 'Have Line',
  notHaveLine: 'Not Have Line',
  triggerUrl: 'Webpopup Trigger Url',
  frequencyOfDisplay: 'Frequency of Display Per Day',
  nameAndPrice: 'Name and Price',
  showProductName: 'Show Product Name',
  showProductPrice: 'Show Product Price',
  showProductSpecailPrice: 'Show Product Special Price',
  specialPrice: 'Special Price',
  edmLinkMsg:
    'The URL link must be wrapped with a hyperlink, otherwise there will be no tracking injection in the URL',
  inFollowingDays: 'In Following Days',
  withinDays: 'Within Days',
  customField: 'Custom Field',
  fieldName: 'Field Name',
  dataCategory: 'Data Category',
  chooseDataCategory: 'Choose Data Category',
  fieldType: 'Field Type',
  fieldSpec: 'Field Spec',
  chooseFieldType: 'Choose Field Type',
  boolean: 'Boolean',
  avg: 'Avg',
  sum: 'Sum',
  clone: 'Clone',
  priority: 'Priority',
  completed: 'Completed',
  failed: 'Failed',
  running: 'Running',
  inProgress: 'In Progress',
  nextDays: 'Next Days',
  previousStep: 'Previous Step',
  nextStep: 'Next Step',
  description: 'Description',
  sentInLast30Days: 'Sent In Last 30 Days',
  revenueInLast30Days: 'Revenue In Last 30 Day',
  today: 'Today',
  yesterday: 'Yesterday',
  last7Days: 'Last 7 Days',
  last30Days: 'Last 30 Days',
  containToday: 'Contain Today',
  marketingFunnel: 'Marketing Funnel',
  entering: 'Entering',
  registration: 'Registration',
  pageview: 'Pageview',
  session: 'Session',
  addToCart: 'Add to Cart',
  checkout: 'Checkout',
  people: 'People',
  allAudience: 'All Audience',
  tagInAudiences: 'Tag In Audiences',
  deleteTagLabel: 'Are you sure you want to delete',
  workflowUsingTag: 'Workflows that Using the Tag',
  workflowList: 'Workflow List',
  openRevenue: 'Open Conversion Revenue',
  sendCost: 'Send Cost',
  marketingCost: 'Marketing Cost',
  earningsRate: 'Percentage of Revenue',
  decimal: 'Decimal',
  preorderProduct: 'Preorder Product',
  importPreorderProduct: 'Import Preorder Product',
  flashDiscountedProduct: 'Flash Discounted Product',
  importFlashDiscountedProductFirst: 'Import Flash Discounted Product First',
  dailySyncLineUser: 'Daily Sync Line User',
  dailySyncLineUserAndTag: 'Daily Sync Line User and Tag',
  roas: 'ROAS',
  upload: 'Upload',
  addDialog: "Let's Create a New Dialog!",
  personalInformation: 'Personal Information',
  sendNotificationTest: 'Send Notification Test',
  relativeTimeDefaultRangeReminder: 'Relative Time Default Range Reminder',
  previousDates: 'Previous Dates',
  futureDates: 'Future Dates',
  expenseRecord: 'Expense Record',
  totalSpending: 'Total Spending',
  lastSpending: 'Last Spending',
  lastBuyingCycle: 'Last Buying Cycle',
  channelInfo: 'Channel Info',
  subscriptionStatus: 'Subscription Status',
  giftVoucher: 'Gift Voucher',
  giftVoucherName: 'Gift Voucher Name',
  releaseTime: 'Release Time',
  giftVoucherReleaseTime: 'Gift Voucher Release Time',
  expirationTime: 'Expiration Time',
  lastUpdateTime: 'Last Update Time',
  isRedeemed: 'Is Redeemed',
  userJourney: 'User Journey',
  amountOfMoney: 'Amount of Money',
  times: 'Times',
  confirm: 'Confirm',
  activate: 'Activate',
  deactivate: 'Deactivate',
  editHistory: 'Edit History',
  fontSize: 'Font Size',
  color: 'Color',
  totalOpen: 'Total Open',
  totalClick: 'Total Click',
  totalConversionClickRevenue: 'Total Conversion Click Revenue',
  audienceLevel: 'Audience Level',
  audienceRank: 'Audience Ranking',
  aiAudienceCount: 'Total AI Audience Count',
  top: 'Top',
  audienceWithQuantifier: 'Audience With Quantifier',
  aiNodeRange1: 'Range From',
  aiNodeRange2: 'to',
  aiChannelSelect: 'AI Select Channel',
  audienceContactInfo: 'Audience Contact Information',
  totalAudience: 'Total Audience',
  hasLineCount: 'Has Line Count',
  hasEmailCount: 'Has Email Count',
  hasSmsCount: 'Has SMS Count',
  subscriberCount: 'Subscriber Count',
  newSubscriberCount: 'New Subscriber Count',
  nameAudience: 'Name Audience',
  tester: 'Tester Member',
  pricing: 'Pricing',
  integration: 'Integration',
  caseStudy: 'Case Study',
  optional: 'Optional',
  required: 'Required',
  company: 'Company',
  companyName: 'Company Name',
  submit: 'Submit',
  moveWorkflow: 'Move Workflow',
  workflowFolder: 'Workflow Folder',
  moveToFolder: 'Move To Folder',
  uncategorized: 'Uncategorized',
  chooseTagCategory: 'Choose A Tag Category',
  tagCategory: 'Tag Category',
  track: 'Track',
  tracking: 'Tracking',
  untrack: 'Untrack',
  labelGroup: 'Label Group',
  labelGroupName: 'Label Group Name',
  insight: 'Insight',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  quarterly: 'Quarterly',
  yearly: 'Yearly',
  retentionRate: 'Retention Rate',
  retentionCumulativeRate: 'Retention Cumulative Rate',
  pageviewCount: 'Pageview Count',
  pageviewCumulativeCount: 'Pageview Cumulative Count',
  conversion: 'Conversion',
  conversionCumulativeRate: 'Conversion Cumulative Rate',
  conversionRevenue: 'Conversion Revenue',
  conversionCumulativeRevenue: 'Conversion Cumulative Revenue',
  retentionRateDesc: 'Retention Rate Description',
  retentionCumulativeRateDesc: 'Retention Cumulative Rate Description',
  pageviewCountDesc: 'Pageview Count Description',
  pageviewCumulativeCountDesc: 'Pageview Cumulative Count Description',
  conversionRateDesc: 'Conversion Rate Description',
  conversionCumulativeRateDesc: 'Conversion Cumulative Rate Description',
  conversionRevenueDesc: 'Conversion Revenue Description',
  conversionCumulativeRevenueDesc: 'Conversion Cumulative Revenue Description',
  anonymousVisitor: 'Anonymous Visitor',
  periodRevenueDesc: 'Period Revenue Description',
  periodSessionDesc: 'Period Session Description',
  periodPageviewDesc: 'Period Pageview Description',
  periodConversionRateDesc: 'Period Conversion Rate Description',
  periodTransactionDesc: 'Period Transaction Description',
  periodRevenuePerTransactionDesc: 'Period Revenue Per Transaction Description',
  periodChangeDesc: 'Period Change Description',
  avgConversionRate: 'Average Conversion Rate',
  permissionManagement: 'Permission Management',
  permissionSetting: 'Permission Setting',
  permissionRecord: 'Permission Record',
  permissionEditor: 'Permission Editor',
  permissionTarget: 'Permission Target',
  changePermission: 'Change Permission',
  openPermission: 'Open Permission',
  closePermission: 'Close Permission',
  editedTime: 'Edited Time',
  addUser: 'Add User',
  restore: 'Restore',
  areYouSureYouWantToRestore: 'Are you sure you want to restore',
  passwordRule: 'Password Rule',
  passwordRule1: 'Password Rule 1',
  passwordRule2: 'Password Rule 2',
  passwordRule3: 'Password Rule 3',
  msgPasswordNotLegal: 'Msg Password Not Legal',
  weAreSorry: 'We Are Sorry',
  unauthorizedMessage1: 'Unahthorized Message 1',
  unauthorizedMessage2: 'Unahthorized Message 2',
  exportAudienceformation: 'Export Audience Information',
  auditWorkflow: 'Audit Workflow',
  messenger: 'Messenger',
  messengerAccessToken: 'Messenger Access Token',
  projectUuid: 'Project UUID',
  sendMessengerTest: 'Send Messenger Test',
  messengerProvider: 'Messenger Provider',
  messengerPsid: 'Messenger PSID',
  messengerGosky: 'Messenger Provider Gosky',
  imageTitle: 'Image Title',
  imageText: 'Image Text',
  button: 'Button',
  buttonUrl: 'Button Url',
  addButton: 'Add Button',
  chooseMessengerGroup: 'Choose Messenger Group',
  chooseMessengerTemplate: 'Choose Messenger Template',
  fanPage: 'Fan Page',
  disableSuffix: 'Disable Suffix',
  mergeKey: 'Merge Key',
  uploadSuffix: 'Upload Suffix',
  dropFilesHere: 'Drop Files Here',
  maxSize: 'Max Size',
  productName: 'Product Name',
  currency: 'Currency',
  conversions: 'Conversions',
  numOfSales: 'Quantity of Sales',
  numOfPageviews: 'Number Of Pageview',
  featuredFavorites: 'Featured Favorites',
  bestSellersAndRelatedProducts: 'Best Sellers and Related Products',
  highlyExposedProductsAndRelatedProducts:
    'Highly Exposed Products and Related Products',
  totalConversionRevenue: 'Total Conversion Revenue',
  mostRelevantPurchasedProductName: 'Most Relevant Purchased Product Name',
  selectLabels: 'Select Labels',
  memberLabels: 'Member Labels',
  productLabels: 'Product Labels',
  msgUserError: 'User Error',
  msgSendSuccessfully: 'Send Successfully',
  msgCreateSuccessfully: 'Create Successfully',
  msgUpdateSuccessfully: 'Update Successfully',
  msgDeleteSuccessfully: 'Delete Successfully',
  msgScheduledTimeHasPassed: 'Msg Scheduled Time Has Passed',
  msgRealTimeTrackTimeHasPassed:
    'Msg Real-Time Tracking Execution Time Has Passed',
  msgRegionOfSearchExceedLimit: 'Msg Region Of Search Exceed The Limit',
  msgWrongTagNameFormat: 'Msg Wrong Format of Tag Name',
  timezone: 'Timezone',
  msgRequiredFieldsAreMissing: 'Required Fields Are Missing',
  msgPleaseCompleteAllRequiredFields: 'Please Complete All Required Fields',
  msgNeedAtLeastOneTag: 'Need Add At Least One Tag',
  msgActiveWorkflowSuccess: 'Active Workflow Success',
  msgPasswordsDoesNotMatch: 'Passwords Does Not Match',
  msgCurrentPasswordInvalid: 'Current Password Invalid',
  msgPleaseSelectSiteYouWantToMerge: 'Please Select Site You Want To Merge',
  msgCanNotGetHTMLContent: 'Can Not Get HTML Content',
  msgProductFeedDataSyncSuccessfully: 'Product Feed Data Sync Successfully',
  msgDateTimeInvalid: 'DateTime Invalid',
  msgNameCanNotContainAnySpace: 'Name Can Not Contain Any Space',
  msgBeingUsedByFollowingWorkflows: 'Being Used By Following Workflows',
  msgStopWorkflowConfirm: 'Are You Sure You Want To Stop The Workflow',
  msgUploadFileTypeError:
    'Import format error, please change the file type and upload again.',
  msgCannotIncludeUnderscores: 'The field name cannot include underscores',
  msgWorkflowWithMoreThanOneTrigger:
    'Workflow should only contains one starting node',
  msgWorkflowWithEndlessLoop:
    'Cycle detected in workflow, please revise it before activation',
  msgExpiredTime:
    'The expiration time you set has expired, and please select a time in the future.',
  sumTotal: 'Sum Total',
  visitedAudienceCount: 'Visited Audience Count',
  taggedAudienceCount: 'Tagged Audience Count',
  taggedGroupAudienceCount: 'Tagged Group Audience Count',
  taggedRevenue: 'Tagged Revenue',
  taggedGroupRevenue: 'Tagged Group Revenue',
  averageContributionAmount: 'Average Contribution Amount',
  orderProductFeed: 'Order Product Feed',
  dateOrdered: 'Date Ordered',
  orderNumber: 'Order Number',
  orderTotal: 'Order Total',
  orderProductId: 'Order Product Id',
  orderLatestModifiedDate: 'Order Latest Modified Date',
  mostRecentOrder: 'Most Recent Order',
  mostRecentUpdatedOrder: 'Most Recent Updated Order',
  productLabelField: 'Product Label Field',
  priceDisplayMethod: 'Price Display Method',
  roundToTheNearestWholeNumber: 'Round to the nearest whole number',
  originalPriceForProductFeed: 'Original Price For ProductFeed',
  emailSubscriptionOption: 'Synchronized Email Subscription Option',
  onlyUpdateUnsubscribedEmail:
    'Members who only sync but have not subscribed the emails',
  apiConnectionSettings: 'API Connection Settings',
  confirmCleanCanvas: 'Are you sure you want to clean the canvas?',
  verificationCode: 'Verification Code',
  incorrectVerificationCode: 'Incorrect Verification Code',
  exportedRecords: 'Exported Records',
  executionTime: 'Execution Time',
  runReport: 'Run Report',
  timeRange: 'Time Range',
  updateInfo: 'Updating information',
  makingReport: 'Making Report',
  performanceChart: 'Performance Chart',
  addChart: 'Add Chart',
  chartSettings: 'Chart Settings',
  chartName: 'Chart Name',
  chartType: 'Chart Type',
  lineChart: 'Line Chart',
  stackedBarChart: 'Stacked Bar Chart',
  xAxis: 'X Axis',
  yAxis: 'Y Axis',
  timeUnit: 'Time Unit',
  dataDimension: 'Data Dimension',
  timePeriodComparison: 'Time Period Comparison',
  downloadImage: 'Download Image',
  changeImage: 'Change Image',
  chooseTemplate: 'Choose Template',
  custom: 'Custom',
  square: 'Square',
  changeTemplate: 'Change Template',
  productStatReport: 'Product Stat Report',
  productStatReportName: 'Product Stat Report Name',
  productStatReportList: 'Product Stat Report List',
  create: 'Create',
  createdDate: 'Created Date',
  openReviewAllNodesMode: 'Open Review All Nodes Mode',
  closeReviewAllNodesMode: 'Close Review All Nodes Mode',
  verify: 'Verify',
  twoFactorAuth: 'Two Factor Auth',
  deactivate2FA: 'Deactivate 2FA',
  msgLoginWillExpire: 'Msg Login Will Expire',
  msgLoginExpired: 'Msg Login Expired',
  msgPleaseDownloadAuthyApp: 'Msg Please Download Authy App',
  msgPleaseScanQrCode: 'Msg Please Scan Qr Code',
  msgConfirmCancel2FA: 'Msg Confirm Cancel 2FA',
  myMobilePlatform: 'My Mobile Platform',
  msgAfterDownloadAuthyApp: 'Msg After Download Authy App',
  customerJourneyEndTime: 'workflow.CustomerJourneyEndTime',
  endTime: 'End Time',
  endTimeSuggestionMsg: 'endTimeSettingSuggestionMsg',
  listOfCopywritingMaterials: 'List of Copywriting Materials',
  operationRecord: 'Operation Record',
  iSee: 'I see',
  addWorkflowFolder: 'Add Workflow Folder',
  editWorkflowFolder: 'Edit Workflow Folder',
  ONL: 'Online',
  OFL: 'Offline',
  asyncAPIFailed: 'The server is busy now and please try again!',
  approvalStatus: 'Approval Status',
  enableStatus: 'Enable Status',
  waiting: 'Waiting',
  return: 'Return',
  passThrough: 'Pass Through',
  returned: 'Returned',
  auditAuthority: 'Audit Authority',
  reviewApplication: 'Review Application',
  reviewCancelled: 'Review Cancelled',
  passAndStart: 'Pass Through and Activate',
  enableNotes: 'Enable Notes',
  passWarningMsg: 'Workflow Audit Pass Warning Message',
  enableNowMsg: 'Enable Now Message',
  returnCommentMsg: 'Return Comment Message',
  auditResultsRecord: 'Record of Audit Results',
  reportByChannel: 'Report By Channel',
  reportByWorkflow: 'Report By Workflow',
  totalRevenue: 'Total Revenue',
  timePeriod: 'Time Period',
  chooseFolderAndWorkflow: 'Choose Folder and Workflow',
  chooseTimePeriod: 'Choose Time Period',
  moveTheTemplate: 'Move the template',
  copyTheTemplate: 'Copy the template',
  currentFolder: 'Current Folder',
  destinationFolder: 'Destination Folder',
  moveTo: 'Move to',
  dataName: 'Data Name',
  advertisement: 'Advertisement',
  fbAds: 'Facebook Ads',
  accessToken: 'Access Token',
  appNumber: 'App Number',
  appKey: 'App Key',
  adAccountNumber: 'Ad Account Number',
  additionalDescription: 'Additional Description',
  cascadeSetting: 'Cascade Setting',
  copyWebhookURLMsg: 'Copy Webhook URL Message',
  copyLink: 'Copy Link',
  surveySettingURL: 'Survey Setting URL',
  detailInfoMsg: 'Detail Info Message',
  copiedSuccessfully: 'Link Copied Successfully',
  surveyResults: 'Survey Results',
  numberOfQuestions: 'Number of Questions in the Survey',
  fillInDate: 'Fill in Date',
  subject: 'Subject',
  answers: 'Answers',
  noSurvey: 'There is no survey currently.',
  googleAds: 'Google Ads',
  'editor.SizeReminder.width1200px': 'editor SizeReminder width1200px',
  'editor.CreateTemplate.dropdown.AdvancedHTML':
    'editor CreateTemplate dropdown AdvancedHTML',
  'editor.CreateTemplate.dropdown.AdvancedConditionTrigger':
    'editor CreateTemplate dropdown AdvancedConditionTrigger',
  'editor.CreateTemplate.dropdown.Basic':
    'editor CreateTemplate dropdown Basic',
};

/**
 * A util function to generate an object containing all entries of languages and their correspoding key value pairs
 * @param {string} localeDir the relative path to your po files e.g. `path.join(__dirname, '../locales')`
 * @param {string} poFileName po file name (including the extension) e.g. `test.po`
 * @returns {Record<string, Record<string, string>>} a collection of your translation
 */
const getI18NObject = (localeDir, poFileName) => {
  const locales = fs.readdirSync(localeDir);
  return locales.reduce((acc, currentDir) => {
    const poFile = fs.readFileSync(
      path.join(localeDir, currentDir, poFileName),
      {
        encoding: 'utf-8',
      }
    );

    // output directly from po file
    const data = Object.entries(
      gettextParser.po.parse(poFile).translations['']
    ).reduce((acc, [key, value]) => {
      acc[key] = value.msgstr[0];
      return acc;
    }, {});

    // output from remapping key of i18nkeys
    const langobj = {};
    for (const key in inconsistentI18NKeys) {
      langobj[key] = data[inconsistentI18NKeys[key]];
    }

    acc[currentDir] = { ...data, ...langobj };
    return acc;
  }, {});
};

/**
 * A util function to look up whether (1) the trnaslation key exists in the language (2) the corresponding value is not empty (string)
 * @param {(string)[]} transKeys the translation key you'd like to look up
 * @param {string[]} languages an array including all the language entries
 * @param {Record<string, Record<string, string>} I18NObject the returned value of `getI18NObject`
 * @returns {Record<string,string[]>} an array listing all missing languages
 */
const getMissingLangs = (transKeys, languages, I18NObject) => {
  if (transKeys === 0) return {};

  return transKeys.reduce((acc, key) => {
    const missingLanguages = languages.reduce((acc, language) => {
      if (
        !(key in I18NObject[language]) ||
        I18NObject[language][key] === '' ||
        !I18NObject[language][key]
      ) {
        acc.push(language);
      }

      return acc;
    }, []);

    if (missingLanguages.length !== 0) {
      acc[key] = missingLanguages;
    }
    return acc;
  }, {});
};

/**
 * A helper function to digest template lieteral node and get the final output
 * @param {TemplateElement[]} quasis quasis property in ast
 * @param {Expression[]} expressions expression property in ast
 * @returns {string} the calculated value of tempalte literal
 */
const getTemplateStringValue = (quasis, expressions) => {
  return quasis
    .map((item, i) => {
      if (i === quasis.length - 1) return item.value.raw;

      const matchingExp = expressions.find(
        (exp) => item.range[1] === exp.range[0]
      );
      return item.value.raw + (matchingExp.value ?? matchingExp.name);
    })
    .join('');
};

/**
 *
 * @param {CallExpressionArgument} argument0 the first argument of node (node.arguments[0])
 * @returns {string[]} the extracted keys
 */
const getTransKeys = (argument0) => {
  const _getTransKeys = () => {
    try {
      const type = argument0?.type;
      const parent = argument0?.parent;

      if (type === 'TemplateLiteral') {
        const value = getTemplateStringValue(
          argument0.quasis,
          argument0.expressions
        );
        return [value];
      }

      if (type === 'ArrayExpression') {
        const keys = argument0.elements.map((element) => {
          if (element.type === 'TemplateElement') {
            return getTemplateStringValue(element.quasis, element.expressions);
          }
          if (element.type === 'Literal') {
            return element.value;
          }
        });
        return keys;
      }

      if (type === 'Identifier' && parent?.object?.name === 'I18N') {
        return [argument0.name];
      } else {
        return [argument0.value];
      }
    } catch (e) {
      console.log(e);
      return [];
    }
  };

  return _getTransKeys().filter(Boolean);
};

// generate error message
/**
 * Log out the error message in ESLint console
 * @param {Error | any} error error object or anything
 * @param {string} filename the filename where this function is working on
 */
const logErrorMessage = (error, filename = '') => {
  console.log(`🔴🔴🔴 Error occured in ${filename}`);
  if (error instanceof Error) {
    console.log(error);
    console.log(error.message);
  } else {
    console.log(error);
  }
  console.log('\n');
};

// eslint-disable-next-line no-undef
module.exports = {
  getI18NObject,
  getTransKeys,
  getMissingLangs,
  logErrorMessage,
};
