name: Translation CI Checker
run-name: Simple JS Script
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Installation
        run: npm i

      - uses: GrantBirki/git-diff-action@v2.1.0
        id: git-diff-action
        with:
          search_path: src
          json_diff_file_output: diff.json
          file_output_only: 'true'

      # Print the diff in JSON format
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: echo ${{ steps.git-diff-action.outputs.json-diff-path }} &&  cat $DIFF

      - name: Check whether translation keys are missing
        env:
          JSON-DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: npm run test:locale
